type Films = {
    filmNumber: string,
    reference: string,
    releaseDate: string,
    filmTitle: string,
    synopsis: string,
    production: string,
    director: string[], 
    producer: string[]
}

type Film = {
    filmNumber: string,
    reference: string,
    releaseDate: string,
    filmTitle: string,
    synopsis: string,
    production: string,
    director: string[],
    producer: string[],
    cast: string,
    script: string,
    camera: string,
    editor: string,
    music: string,
    story: string,
    dialogue: string,
    assistantDirector: string,
    lyrics: string,
    songs: string,
    makeup: string,
    artDirector: string,
    audioController: string,
    title: string,
    theaters: string,
    awardsPresidential: string,
    awardsSarasaviya: string,
    awardsOcic: string,
    awardsOthers: string,
    festivals: string,
    article: string,
    critics: string,
    others: string,
    special: string,
    poster: string,
    image: string,
    acknowledgement: string
    payOffLine: string,
    lastUpDate: string
}
